name: optibox-backend

services:
  spring-app:
    build: ./spring-app
    container_name: spring-app
    ports:
      - "${SPRING_PORT}:8000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mariadb://db:3306/${MYSQL_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${MYSQL_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQL_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - optibox-shared-network

  db:
    image: mariadb:latest
    container_name: db
    ports:
      - "3307:3306"
    volumes:
      - ./docker-config/databases:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MARIADB_AUTO_UPGRADE: "1"
    healthcheck:
      test: ["CMD-SHELL", "if [ -d /var/lib/mysql/moyens_levage ]; then exit 0; else exit 1; fi"] # Check if the database is up
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - optibox-shared-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "${PMA_PORT}:80"
    environment:
      PMA_HOST: "${PMA_HOST}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - optibox-shared-network

networks:
  optibox-shared-network:
    external: true
